//
//  CarData.swift
//  Vandi_2
//
//  Created by user2 on 27/02/24.
//

import Foundation

let cars: [Car] = [
    Car(
        
        govRegistraionNumber: "KA01AB1234",
        carName: "Maruti Suzuki Swift",
        carRating: 4.5,
        reviewsCount: 120,
        brand: "Maruti Suzuki",
        modelName: "Swift",
        modelYear: "2022",
        pricePerDay: 1200,
        pricePerHour: 150,
        description: "A popular hatchback in India known for its fuel efficiency and stylish design.",
        mainImageName: "swift_main_image",
        imagesNames: ["swift_image1", "swift_image2", "swift_image3"],
        insurance: "Comprehensive",
        maxDistance: 250.0,
        numberOfSeats: 5,
        numberOfDoors: 5,
        transmissionType: "Manual",
        GasType: "Petrol",
        hostName: "Maruti Suzuki Dealership",
        HostImageName: "maruti_suzuki_logo",
        HostJoinDate: "2020-01-15",
        isFavorite: false,
        airCondition: true,
        colour: "Red",
        milage: 20.5,
        lastServiceDate: Date(),
        vendorId: 101,
        maxSpeed: 160.0,
        horsePower: 85.0
    ),
    Car(
            
            govRegistraionNumber: "DL02CD5678",
            carName: "Hyundai Venue",
            carRating: 4.2,
            reviewsCount: 95,
            brand: "Hyundai",
            modelName: "Venue",
            modelYear: "2022",
            pricePerDay: 1500,
            pricePerHour: 180,
            description: "A compact SUV with modern features and a sleek design.",
            mainImageName: "venue_main_image",
            imagesNames: ["venue_image1", "venue_image2", "venue_image3"],
            insurance: "Third Party",
            maxDistance: 300.0,
            numberOfSeats: 5,
            numberOfDoors: 5,
            transmissionType: "Automatic",
            GasType: "Diesel",
            hostName: "Hyundai Dealership",
            HostImageName: "hyundai_logo",
            HostJoinDate: "2019-11-20",
            isFavorite: false,
            airCondition: true,
            colour: "Silver",
            milage: 18.0,
            lastServiceDate: Date(),
            vendorId: 102,
            maxSpeed: 170.0,
            horsePower: 90.0
        ),
    Car(
            
            govRegistraionNumber: "MH03EF9102",
            carName: "Honda City",
            carRating: 4.3,
            reviewsCount: 110,
            brand: "Honda",
            modelName: "City",
            modelYear: "2022",
            pricePerDay: 1800,
            pricePerHour: 200,
            description: "A popular sedan known for its comfortable ride and advanced features.",
            mainImageName: "city_main_image",
            imagesNames: ["city_image1", "city_image2", "city_image3"],
            insurance: "Comprehensive",
            maxDistance: 280.0,
            numberOfSeats: 5,
            numberOfDoors: 4,
            transmissionType: "CVT",
            GasType: "Petrol",
            hostName: "Honda Dealership",
            HostImageName: "honda_logo",
            HostJoinDate: "2020-03-10",
            isFavorite: false,
            airCondition: true,
            colour: "Blue",
            milage: 16.5,
            lastServiceDate: Date(),
            vendorId: 103,
            maxSpeed: 160.0,
            horsePower: 115.0
        ),
        Car(
            
            govRegistraionNumber: "TN07GH4567",
            carName: "Tata Nexon",
            carRating: 4.0,
            reviewsCount: 80,
            brand: "Tata",
            modelName: "Nexon",
            modelYear: "2022",
            pricePerDay: 1600,
            pricePerHour: 180,
            description: "An SUV with a bold design and strong safety features.",
            mainImageName: "nexon_main_image",
            imagesNames: ["nexon_image1", "nexon_image2", "nexon_image3"],
            insurance: "Third Party",
            maxDistance: 320.0,
            numberOfSeats: 5,
            numberOfDoors: 5,
            transmissionType: "Manual",
            GasType: "Diesel",
            hostName: "Tata Motors",
            HostImageName: "tata_logo",
            HostJoinDate: "2019-09-25",
            isFavorite: false,
            airCondition: true,
            colour: "White",
            milage: 21.0,
            lastServiceDate: Date(),
            vendorId: 104,
            maxSpeed: 170.0,
            horsePower: 110.0
        ),
        Car(
            
            govRegistraionNumber: "KL05IJ7890",
            carName: "Ford EcoSport",
            carRating: 4.1,
            reviewsCount: 92,
            brand: "Ford",
            modelName: "EcoSport",
            modelYear: "2022",
            pricePerDay: 1700,
            pricePerHour: 190,
            description: "A compact SUV offering a sporty look and enjoyable driving experience.",
            mainImageName: "ecosport_main_image",
            imagesNames: ["ecosport_image1", "ecosport_image2", "ecosport_image3"],
            insurance: "Comprehensive",
            maxDistance: 300.0,
            numberOfSeats: 5,
            numberOfDoors: 5,
            transmissionType: "Automatic",
            GasType: "Petrol",
            hostName: "Ford Dealership",
            HostImageName: "ford_logo",
            HostJoinDate: "2021-01-05",
            isFavorite: false,
            airCondition: true,
            colour: "Black",
            milage: 17.5,
            lastServiceDate: Date(),
            vendorId: 105,
            maxSpeed: 165.0,
            horsePower: 125.0
        )
    
    
]
